---
# Playbook: 01_provision_infra.yml
# Purpose:  Provision AWS EC2 instances and EBS volumes for SAP HANA secondary and optional app server.
# Notes:    Uses the amazon.aws collection. Expects AWS credentials via role, profile, or env vars.
#           After provisioning, update inventories/dev/hosts.ini with the actual private IPs if needed.

- name: Provision HANA and app servers on AWS
  hosts: localhost                       # Run locally (Ansible control node)
  connection: local
  gather_facts: false
  collections:
    - amazon.aws

  vars:
    # Tags help with cost allocation and cleanup
    common_tags:
      Project: "sap-hana-migration"
      Env: "dev"

  tasks:
    - name: Create HANA EC2 instance
      # Module: ec2_instance (creates or ensures an EC2 instance exists)
      ec2_instance:
        name: "hana-aws-1"                          # Name tag visible in AWS Console
        image_id: "{{ rhel_for_sap_ami }}"          # RHEL for SAP Solutions AMI
        instance_type: "{{ hana_instance_type }}"   # HANA-certified family recommended
        key_name: "{{ key_name }}"                  # SSH keypair for access
        region: "{{ aws_region }}"
        profile: "{{ aws_profile | default(omit) }}"
        # Place the HANA host in a private subnet
        subnet_id: "{{ subnets[0] }}"
        security_group_ids: "{{ security_groups }}"
        # EBS layout: root + dedicated data/log volumes for HANA
        volumes:
          - device_name: /dev/sda1
            volume_size: "{{ hana_root_volume_size }}"
            volume_type: gp3
          - device_name: /dev/xvdb
            volume_size: "{{ hana_data_volume_size }}"
            volume_type: io2
          - device_name: /dev/xvdc
            volume_size: "{{ hana_log_volume_size }}"
            volume_type: io2
        tags: "{{ common_tags | combine({'Role': 'SAP-HANA'}) }}"
        wait: true
      register: hana_ec2

    - name: Create Application Server EC2 instance
      ec2_instance:
        name: "app-aws-1"
        image_id: "{{ rhel_for_sap_ami }}"
        instance_type: "{{ app_instance_type }}"
        key_name: "{{ key_name }}"
        region: "{{ aws_region }}"
        profile: "{{ aws_profile | default(omit) }}"
        subnet_id: "{{ subnets[1] }}"
        security_group_ids: "{{ security_groups }}"
        volumes:
          - device_name: /dev/sda1
            volume_size: 100
            volume_type: gp3
        tags: "{{ common_tags | combine({'Role': 'SAP-App'}) }}"
        wait: true
      register: app_ec2

    - name: Output provisioned instance IPs (copy into inventory if needed)
      debug:
        msg:
          - "HANA private IP: {{ hana_ec2.instances[0].private_ip_address | default('UNKNOWN') }}"
          - "APP  private IP: {{ app_ec2.instances[0].private_ip_address | default('UNKNOWN') }}"
