---
# Playbook: 02_rhel_preconfigure.yml
# Purpose:  Prepare RHEL for SAP workloads using Red Hat SAP Day-1 roles.
#           Applies general SAP tuning, plus HANA-specific and NetWeaver-specific preconfiguration.
# Notes:    Requires 'redhat.sap_install' collection (see collections/requirements.yml).
#           Run after EC2 provisioning and after you can SSH to the hosts.

- name: Common OS preconfigure for SAP (all nodes)
  hosts: hana:app
  become: true
  gather_facts: true
  collections:
    - redhat.sap_install

  tasks:
    - name: Apply general SAP OS settings (packages, kernel params, limits)
      include_role:
        name: redhat.sap_install.sap_general_preconfigure

- name: HANA-specific OS preconfiguration
  hosts: hana
  become: true
  collections:
    - redhat.sap_install
  tasks:
    - name: Apply HANA tuning (HugePages, I/O schedulers, etc.)
      include_role:
        name: redhat.sap_install.sap_hana_preconfigure

- name: NetWeaver-specific OS preconfiguration (if app server is used)
  hosts: app
  become: true
  collections:
    - redhat.sap_install
  tasks:
    - name: Apply NetWeaver OS requirements
      include_role:
        name: redhat.sap_install.sap_netweaver_preconfigure
