---
# Playbook: 03_install_hana.yml
# Purpose:  Install SAP HANA on the AWS HANA node using the Red Hat role that wraps HDBLCM.
# Notes:    Ensure SAP HANA installation media is available at sap_hana_media_path on the target,
#           or mount it from the control node. Use Ansible Vault for real passwords.

- name: Install SAP HANA on AWS secondary
  hosts: hana
  become: true
  collections:
    - redhat.sap_install

  vars:
    sap_hana_sid: "{{ hostvars[inventory_hostname].sap_sid | default('PRD') }}"
    sap_hana_instance_nr: "{{ hostvars[inventory_hostname].sap_instance_nr | default('00') }}"
    sap_hana_install_media_path: "{{ sap_hana_media_path }}"
    sap_hana_system_password: "{{ sap_master_password }}"
    sap_hana_components: "all"    # customize as needed

  tasks:
    - name: Ensure HANA media path exists
      file:
        path: "{{ sap_hana_install_media_path }}"
        state: directory

    - name: Install SAP HANA using HDBLCM (via role)
      include_role:
        name: redhat.sap_install.sap_hana_install
      vars:
        # Most parameters are inherited from vars above; add advanced options as needed
        # Consult the role's documentation for product/component selection
        sap_hana_sid: "{{ sap_hana_sid }}"
        sap_hana_instance_nr: "{{ sap_hana_instance_nr }}"
        sap_hana_install_media_path: "{{ sap_hana_install_media_path }}"
        sap_hana_system_password: "{{ sap_hana_system_password }}"
        sap_hana_components: "{{ sap_hana_components }}"
