---
# Playbook: 04_configure_hsr.yml
# Purpose:  Configure SAP HANA System Replication (HSR) between on-prem primary and AWS secondary.
# Notes:    Make sure the primary host is reachable (network/VPN), and proper firewall rules are in place.

- name: Configure HANA System Replication (HSR)
  hosts: hana
  become: true
  collections:
    - redhat.sap_install

  vars:
    # Expect on-prem details to be present in inventory/group_vars or passed via --extra-vars
    hana_primary_host: "{{ hostvars['hana-onprem-1'].ansible_host | default('PRIMARY_IP') }}"
    hana_secondary_host: "{{ inventory_hostname }}"
    sap_sid: "{{ hostvars[inventory_hostname].sap_sid | default('PRD') }}"
    instance_nr: "{{ hostvars[inventory_hostname].sap_instance_nr | default('00') }}"
    system_replication_mode: "sync"  # or 'async'

  tasks:
    - name: Setup HSR between primary and secondary using role
      include_role:
        name: redhat.sap_install.sap_ha_install_hana_hsr
      vars:
        sap_hana_hsr_primary_host: "{{ hana_primary_host }}"
        sap_hana_hsr_secondary_host: "{{ hana_secondary_host }}"
        sap_hana_hsr_sid: "{{ sap_sid }}"
        sap_hana_hsr_instance_nr: "{{ instance_nr }}"
        sap_hana_hsr_mode: "{{ system_replication_mode }}"

    - name: Note
      debug:
        msg:
          - "Verify replication status via hdbnsutil/hdbsql and perform planned takeover when ready."
