name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters
        run: |
          pip install ansible ansible-lint yamllint boto3 botocore

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint
